services:
  bodegas:
    build:
      context: ./microservicio_bodegas
      dockerfile: ./Dockerfile
    ports:
      - "9001:5000"
    volumes:
      - ./microservicio_bodegas:/app
  ventas:
    build:
      context: ./microservicio_ventas
      dockerfile: ./Dockerfile
    ports:
      - "9002:5000"
    volumes:
      - ./microservicio_ventas:/app
  compras:
    build:
      context: ./microservicio_compras
      dockerfile: ./Dockerfile
    ports:
      - "9000:5000"
    depends_on:
      - bodegas
      - ventas
    volumes:
      - ./microservicio_compras:/app
  apigw:
    build:
      context: ./api_gateway
      dockerfile: ./Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - bodegas
      - ventas
      - compras
