services:
  bodegas:
    build:
      context: ./microservicio_bodegas
      dockerfile: ./Dockerfile
    ports:
      - "9001:5000"
    volumes:
      - ./microservicio_bodegas:/app
  ventas:
    build:
      context: ./microservicio_ventas
      dockerfile: ./Dockerfile
    ports:
      - "9002:5000"
    volumes:
      - ./microservicio_ventas:/app
  compras:
    build:
      context: ./microservicio_compras
      dockerfile: ./Dockerfile
    ports:
      - "9000:5000"
    depends_on:
      - bodegas
      - ventas
    volumes:
      - ./microservicio_compras:/app
  usuarios:
    build:
      context: ./microservicio_usuarios
      dockerfile: ./Dockerfile
    ports:
      - "9003:5000"
    volumes:
      - ./microservicio_usuarios:/app
  autorizador:
    build:
      context: ./microservicio_autorizador
      dockerfile: ./Dockerfile
    ports:
      - "9004:5000"
    volumes:
      - ./microservicio_autorizador:/app
  apigw:
    build:
      context: ./api_gateway
      dockerfile: ./Dockerfile
    ports:
      - "9005:5000"
    depends_on:
      - usuarios
      - autorizador
